### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SummerSec** [Marcono1234/codeql-jdk-docker#2]
It is recommended to use https://ghproxy.com/ to accelerate the download speed

**Comment by Marcono1234** [comment]
Thanks for the suggestion, however I think it is more transparent to directly refer to GitHub instead of a third-party site. Therefore I will keep using the GitHub URI.
`git clone` is executed with `--depth 1` (at least when no commit SHA is specified) so that should be fairly fast. If it is too slow, users can use the `--jdk-git-repo` option of this project to use ghproxy.
